os: linux
language: node_js
node_js: '12'
cache: npm
addons:
  chrome: stable

services:
  - xvfb

script:
  - xvfb run -e /dev/stdout -a npm run test  

notifications:
  email:
    on_success: never
    on_failure: never