import { COMMAND_ADJUST, COMMAND_RESET_FILTERS } from './display-filters'
import { COMMAND_MAP_TILE_PROVIDER, COMMAND_HIDPI_SUPPORT, COMMAND_TOGGLE_MAP_VISIBILITY } from './tile-provider'
import { COMMAND_COPY_COORDS } from './clipboard'
import { COMMAND_NEW_POI, COMMAND_NEW_NAI, COMMAND_NEW_TAI } from './poi'
import { COMMAND_IMPORT_LAYER } from './layer'

export default {
  COMMAND_ADJUST,
  COMMAND_RESET_FILTERS,
  COMMAND_MAP_TILE_PROVIDER,
  COMMAND_HIDPI_SUPPORT,
  COMMAND_COPY_COORDS,
  COMMAND_TOGGLE_MAP_VISIBILITY,
  COMMAND_NEW_POI,
  COMMAND_NEW_NAI,
  COMMAND_NEW_TAI,
  COMMAND_IMPORT_LAYER
}
