import { COMMAND_MAP_TILE_PROVIDER, COMMAND_HIDPI_SUPPORT, COMMAND_TOGGLE_MAP_VISIBILITY } from './tile-provider'
import { COMMAND_COPY_COORDS } from './clipboard'
import { COMMAND_IMPORT_LAYER } from './layer'

export default {
  COMMAND_MAP_TILE_PROVIDER,
  COMMAND_HIDPI_SUPPORT,
  COMMAND_COPY_COORDS,
  COMMAND_TOGGLE_MAP_VISIBILITY,
  COMMAND_IMPORT_LAYER
}
